---
title: "Session 5 - PCA and k-means clustering"
author: "Jeppe N Samuelsen"
date: "9 3 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PCA analysis of BLOSUM62 matrix

Loading libraries:
```{r}
library(tidyverse)
library(broom)
```


Load the data:
```{r}
my_url <- "https://www.ncbi.nlm.nih.gov/Class/FieldGuide/BLOSUM62.txt"
bl62 <- read_table(file = my_url, comment = '#') %>%
  rename(aa = X1)
bl62
```

Wrangle and save the data:
```{r}
bl62 <- bl62 %>%
  select(aa:V) %>%
  slice(1:20) %>%
  write_tsv(path = "data/BLOSUM62_ncbi.tsv")
bl62
```

Create PCA object:
```{r}
bl62_pca <- bl62 %>%
  select(-aa) %>%
  prcomp(center = TRUE, scale = TRUE)
bl62_pca
```

Making a scree plot using broom tidy:
```{r}
bl62_pca %>%
  tidy("pcs") %>% 
  ggplot(aes(x = PC, y = percent)) +
  geom_col() +
  theme_bw()
```

Augment using broom:
```{r}
bl62_pca_aug <- bl62_pca %>%
  augment(bl62)
bl62_pca_aug
```

Adding some chemichal classes:
```{r}
get_chem_class <- function(x){
  chem_cols <- c("A" = "Hydrophobic", "R" = "Basic", "N" = "Neutral", "D" = "Acidic",
                 "C" = "sulphur", "Q" = "Neutral", "E" = "Acidic", "G" = "Polar",
                 "H" = "Basic", "I" = "Hydrophobic", "L" = "Hydrophobic", "K" = "Basic",
                 "M" = "sulphur", "F" = "Hydrophobic", "P" = "Hydrophobic", "S" = "Polar",
                 "T" = "Polar", "W" = "Hydrophobic", "Y" = "Polar", "V" = "Hydrophobic")
  return(factor(chem_cols[x]))
}
```

```{r}
bl62_pca_aug <- bl62_pca_aug %>% 
  mutate(chem_class = get_chem_class(aa))
```

```{r}
bl62_pca_aug %>% select(aa, chem_class)
```

Plotting the PCA:
```{r}
bl62_pca_aug %>% 
  ggplot(aes(x = .fittedPC1, y = .fittedPC2, label = aa, colour = chem_class)) +
  geom_text() +
  theme(legend.position = "bottom")
```

